stages:
  - build

default:
  before_script:
    - rustc --version
    - cargo --version

rust-latest:
  stage: build
  image: rust:latest
  tags:
    - rust
  script:
    - cargo build
    - cargo test
