[package]
name = "time-flo"
version = "0.1.0"
edition = "2018"

[dependencies]
adw = { version = "0.1.0-alpha-6", package = "libadwaita" }
gtk = { version = "0.3", package = "gtk4" }
relm4 = { version = "0.2", features = ["libadwaita"] }
relm4-macros = "0.2"
relm4-components = "0.2"